/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.c
 *  subm:  PositionControllerPan
 *  model: PositionControllerPan
 *  expmt: Jiwy
 *  date:  June 11, 2021
 *  time:  3:58:16 PM
 *  user:  20-sim 4.8 Campus License
 *  from:  Universiteit Twente
 *  build: 4.8.3.10415
 **********************************************************/

/* Standard include files */
#include <stdlib.h>

/* 20-sim include files */
#include "pan_model.h"
#include "pan_integ.h"
////#include "pan_funcs.h"
#include "pan_submod.h"
//#include "motionprofiles.h"
//#include "EulerAngles.h"

/* The submodel I/O variables */
int pan_number_of_inputs = 2;
int pan_number_of_outputs = 2;

/* the names of the submodel io variables
   uncomment this part if you need these names
XXString xx_input_names[] = {
	"in",
	"position"
,	NULL
};
XXString xx_output_names[] = {
	"corr",
	"out"
,	NULL
};
*/
/* This function sets the input variables from the input vector */
void pan_CopyInputsToVariables (double *u)
{
	/* Copy the input vector to the input variables */
	pan_V[7] = u[0];		/* in */
	pan_V[8] = u[1];		/* position */

}

/* This function uses the output variables to fill the output vector */
void pan_CopyVariablesToOutputs (double *y)
{
	/* Copy the output variables to the output vector */
	y[0] = 	pan_V[6];		/* corr */
	y[1] = 	pan_V[9];		/* out */

}

/* The initialization function for submodel */
void pan_InitializeSubmodel (double *u, double *y, double t)
{
	/* Initialization phase (allocating memory) */
	pan_initialize = 1;
	pan_steps = 0;
	pan_ModelInitialize ();
	pan_DiscreteInitialize ();

	/* Copy the inputs */
	pan_time = t;
	pan_CopyInputsToVariables (u);

	/* Calculate the model for the first time */
	pan_CalculateInitial ();
	pan_CalculateStatic ();
	pan_CalculateInput ();
	pan_CalculateDynamic ();
	pan_CalculateOutput ();

	/* Set the outputs */
	pan_CopyVariablesToOutputs (y);

	/* End of initialization phase */
	pan_initialize = 0;
}

/* The function that calculates the submodel */
void pan_CalculateSubmodel (double *u, double *y, double t)
{
	/* Copy the inputs */
	pan_time = t;
	pan_CopyInputsToVariables (u);

	/* Calculate the model */
	pan_CalculateInput ();
	pan_DiscreteStep ();
	pan_CalculateOutput ();

	/* Copy the outputs */
	pan_CopyVariablesToOutputs (y);
}

/* The termination function for submodel */
void pan_TerminateSubmodel (double *u, double *y, double t)
{
	/* Copy the inputs */
	pan_time = t;
	pan_CopyInputsToVariables (u);

	/* Calculate the final model equations */
	pan_CalculateFinal ();

	/* Set the outputs */
	pan_CopyVariablesToOutputs (y);

	/* and terminate the model itself (releasing memory) */
	pan_ModelTerminate ();
	pan_DiscreteTerminate ();
}

