/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxmodel.c
 *  model: PositionControllerPan
 *  expmt: Jiwy
 *  date:  June 11, 2021
 *  time:  3:58:16 PM
 *  user:  20-sim 4.8 Campus License
 *  from:  Universiteit Twente
 *  build: 4.8.3.10415
 **********************************************************/

/* This file contains the actual model variables and equations */

/* Note: Alias variables are the result of full optimization
   of the model in 20-sim. As a result, only the real variables
   are used in the model for speed. The user may also include
   the alias variables by adding them to the end of the array:

   double xx_variables[NUMBER_VARIABLES + NUMBER_ALIAS_VARIABLES + 1];
   XXString xx_variable_names[] = {
     VARIABLE_NAMES, ALIAS_VARIABLE_NAMES, NULL
   };

   and calculate them directly after the output equations:

   void XXCalculateOutput (void)
   {
     OUTPUT_EQUATIONS
     ALIAS_EQUATIONS
   }
*/

/* system include files */
#include <stdlib.h>
#include <math.h>
#include <string.h>

/* 20-sim include files */
#include "pan_model.h"
//#include "pan_funcs.h"

/* the global variables */
double pan_start_time = 0.0;
double pan_finish_time = 20.0;
double pan_step_size = 0.01;
double pan_time = 0.0;
int pan_steps = 0;
char pan_initialize = 1;
char pan_major = 1;
char pan_stop_simulation = 0;

/* the variable arrays */
double pan_P[pan_parameters_size];		/* parameters */
double pan_I[pan_initialvalues_size];		/* initial values */
double pan_V[pan_variables_size];		/* variables */
double pan_s[pan_states_size];		/* states */
double pan_R[pan_states_size];		/* rates (or new states) */

/* the names of the variables as used in the arrays above
   uncomment this part if these names are needed
XXString xx_parameter_names[] = {
	"corrGain\\K",
	"PID1\\kp",
	"PID1\\tauD",
	"PID1\\beta",
	"PID1\\tauI",
	"SignalLimiter2\\minimum",
	"SignalLimiter2\\maximum"
,	NULL
};
XXString xx_initial_value_names[] = {
	"PID1\\uD_previous_initial",
	"PID1\\error_previous_initial",
	"PID1\\uI_previous_initial"
,	NULL
};
XXString xx_variable_names[] = {
	"corrGain\\corr",
	"PID1\\output",
	"",
	"PlusMinus1\\plus1",
	"SignalLimiter2\\output",
	"Splitter1\\input",
	"corr",
	"in",
	"position",
	"out"
,	NULL
};
XXString xx_state_names[] = {
	"PID1\\uD_previous",
	"PID1\\error_previous",
	"PID1\\uI_previous"
,	NULL
};
XXString xx_rate_names[] = {
	"",
	"PID1\\error",
	""
,	NULL
};
*/

#if (7 > 8192) && defined _MSC_VER
#pragma optimize("", off)
#endif
void pan_ModelInitialize_parameters(void)
{
	/* set the parameters */
	pan_P[0] = 0.0;		/* corrGain\K */
	pan_P[1] = 2.6;		/* PID1\kp */
	pan_P[2] = 0.05;		/* PID1\tauD */
	pan_P[3] = 0.17;		/* PID1\beta */
	pan_P[4] = 9.0;		/* PID1\tauI */
	pan_P[5] = -0.99;		/* SignalLimiter2\minimum */
	pan_P[6] = 0.99;		/* SignalLimiter2\maximum */

}
#if (7 > 8192) && defined _MSC_VER
#pragma optimize("", on)
#endif

void pan_ModelInitialize_initialvalues(void)
{
	/* set the initial values */
	pan_I[0] = 0.0;		/* PID1\uD_previous_initial */
	pan_I[1] = 0.0;		/* PID1\error_previous_initial */
	pan_I[2] = 0.0;		/* PID1\uI_previous_initial */

}

void pan_ModelInitialize_states(void)
{
	/* set the states */
	pan_s[0] = pan_I[0];		/* PID1\uD_previous */
	pan_s[1] = pan_I[1];		/* PID1\error_previous */
	pan_s[2] = pan_I[2];		/* PID1\uI_previous */

}

void pan_ModelInitialize_variables(void)
{
	/* initialize the variable memory to zero */
	memset(pan_V, 0, pan_variables_size * sizeof(double));
}

/* this method is called before calculation is possible */
void pan_ModelInitialize (void)
{
	pan_ModelInitialize_parameters();
	pan_ModelInitialize_variables();
	pan_ModelInitialize_initialvalues();
	pan_ModelInitialize_states();
}

/* This function calculates the initial equations of the model.
 * These equations are calculated before anything else
 */
void pan_CalculateInitial (void)
{

}

/* This function calculates the static equations of the model.
 * These equations are only dependent from parameters and constants
 */
void pan_CalculateStatic (void)
{

}

/* This function calculates the input equations of the model.
 * These equations are dynamic equations that must not change
 * in calls from the integration method (like random and delay).
 */
void pan_CalculateInput (void)
{

}

/* This function calculates the dynamic equations of the model.
 * These equations are called from the integration method
 * to calculate the new model rates (that are then integrated).
 */
void pan_CalculateDynamic (void)
{
	/* PID1\factor = 1 / (sampletime + PID1\tauD * PID1\beta); */
	pan_V[2] = 1.0 / (pan_step_size + pan_P[2] * pan_P[3]);

	/* PlusMinus1\plus1 = in; */
	pan_V[3] = pan_V[7];

	/* Splitter1\input = position; */
	pan_V[5] = pan_V[8];

	/* corrGain\corr = corrGain\K * Splitter1\input; */
	pan_V[0] = pan_P[0] * pan_V[5];

	/* PID1\error = PlusMinus1\plus1 - Splitter1\input; */
	pan_R[1] = pan_V[3] - pan_V[5];

	/* PID1\uD = PID1\factor * (((PID1\tauD * PID1\uD_previous) * PID1\beta + (PID1\tauD * PID1\kp) * (PID1\error - PID1\error_previous)) + (sampletime * PID1\kp) * PID1\error); */
	pan_R[0] = pan_V[2] * (((pan_P[2] * pan_s[0]) * pan_P[3] + (pan_P[2] * pan_P[1]) * (pan_R[1] - pan_s[1])) + (pan_step_size * pan_P[1]) * pan_R[1]);

	/* PID1\uI = PID1\uI_previous + (sampletime * PID1\uD) / PID1\tauI; */
	pan_R[2] = pan_s[2] + (pan_step_size * pan_R[0]) / pan_P[4];

	/* PID1\output = PID1\uI + PID1\uD; */
	pan_V[1] = pan_R[2] + pan_R[0];

	/* SignalLimiter2\output = (if PID1\output < SignalLimiter2\minimum then SignalLimiter2\minimum else (if PID1\output > SignalLimiter2\maximum then SignalLimiter2\maximum else PID1\output end) end); */
	pan_V[4] = ((pan_V[1] < pan_P[5]) ? 
		/* SignalLimiter2\minimum */
		pan_P[5]
	:
		/* (if PID1\output > SignalLimiter2\maximum then SignalLimiter2\maximum else PID1\output end) */
		((pan_V[1] > pan_P[6]) ? 
			/* SignalLimiter2\maximum */
			pan_P[6]
		:
			/* PID1\output */
			pan_V[1]
		)
	);


	/* increment the step counter */
	pan_steps++;
}

/* This function calculates the output equations of the model.
 * These equations are not needed for calculation of the rates
 * and are kept separate to make the dynamic set of equations smaller.
 * These dynamic equations are called often more than one time for each
 * integration step that is taken. This makes model computation much faster.
 */
void pan_CalculateOutput (void)
{
	/* corr = corrGain\corr; */
	pan_V[6] = pan_V[0];

	/* out = SignalLimiter2\output; */
	pan_V[9] = pan_V[4];

}

/* This function calculates the final equations of the model.
 * These equations are calculated after all the calculations
 * are performed
 */
void pan_CalculateFinal (void)
{

}

/* this method is called after all calculations are performed */
void pan_ModelTerminate(void)
{
}

