/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.h
 *  subm:  PositionControllerTilt
 *  model: PositionControllerTilt
 *  expmt: Jiwy
 *  date:  June 11, 2021
 *  time:  3:58:29 PM
 *  user:  20-sim 4.8 Campus License
 *  from:  Universiteit Twente
 *  build: 4.8.3.10415
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef tilt_SUBMOD_H
#define tilt_SUBMOD_H

/* Our own include files */
#include "tilt_model.h"

/* Submodel I/O variables */
extern int tilt_number_of_inputs;
extern int tilt_number_of_outputs;

/* The names of the variables as used in the arrays above */
//extern XXString tilt_input_names[];
//extern XXString tilt_output_names[];


/* The submodel functions */
void tilt_InitializeSubmodel (double *u, double *y, double t);
void tilt_CalculateSubmodel (double *u, double *y, double t);
void tilt_TerminateSubmodel (double *u, double *y, double t);
void tilt_CopyInputsToVariables (double *u);
void tilt_CopyVariablesToOutputs (double *y);

#endif

