/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.h
 *  subm:  PositionControllerPan
 *  model: PositionControllerPan
 *  expmt: Jiwy
 *  date:  June 11, 2021
 *  time:  3:58:16 PM
 *  user:  20-sim 4.8 Campus License
 *  from:  Universiteit Twente
 *  build: 4.8.3.10415
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the pan_model.c file
*/

#ifndef pan_SUBMOD_H
#define pan_SUBMOD_H

/* Our own include files */
#include "pan_model.h"

/* Submodel I/O variables */
extern int pan_number_of_inputs;
extern int pan_number_of_outputs;

/* The names of the variables as used in the arrays above */
//extern XXString pan_input_names[];
//extern XXString pan_output_names[];


/* The submodel functions */
void pan_InitializeSubmodel (double *u, double *y, double t);
void pan_CalculateSubmodel (double *u, double *y, double t);
void pan_TerminateSubmodel (double *u, double *y, double t);
void pan_CopyInputsToVariables (double *u);
void pan_CopyVariablesToOutputs (double *y);

#endif

