/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxinteg.c
 *  subm:  PositionControllerPan
 *  model: PositionControllerPan
 *  expmt: Jiwy
 *  date:  June 11, 2021
 *  time:  3:58:16 PM
 *  user:  20-sim 4.8 Campus License
 *  from:  Universiteit Twente
 *  build: 4.8.3.10415
 **********************************************************/

/* This file describes the integration methods
   that are supplied for computation.

   Currently the following methods are supported:
   * Euler
   * RungeKutta2
   * RungeKutta4
   but it is easy for the user to add their own
   integration methods with these two as an example.
*/

/* the system include files */
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* our own include files */
#include "pan_integ.h"
#include "pan_model.h"

/* global variables prototypes */
extern double pan_time;
extern double pan_step_size;

#define pan_STATE_SIZE 3

/*********************************************************************
 * Discrete integration method
 *********************************************************************/

/* the initialization of the Discrete integration method */
void pan_DiscreteInitialize (void)
{
	/* nothing to be done */
	pan_major = 1;
}

/* the Discrete integration method itself */
void pan_DiscreteStep (void)
{
	int index;
	/* for each of the supplied states */
	for (index = 0; index < pan_STATE_SIZE; index++)
	{
		/* just a move of the new state */
		pan_s [index] = pan_R [index];
	}
	/* increment the simulation time */
	pan_time += pan_step_size;

	pan_major = 1;

	/* evaluate the dynamic part to calculate the new rates */
	pan_CalculateDynamic ();
}

