/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxfuncs.h
 *  model: PositionControllerPan
 *  expmt: Jiwy
 *  date:  June 11, 2021
 *  time:  3:58:16 PM
 *  user:  20-sim 4.8 Campus License
 *  from:  Universiteit Twente
 *  build: 4.8.3.10415
 **********************************************************/

#ifndef XX_FUNCS_H
#define XX_FUNCS_H

/* Our own include files */
//#include "xxtypes.h"

/* Global constants */
extern char pan_initialize;
extern char pan_major;
extern char pan_stop_simulation;

/* Wrapper functions around strings */
double pan_String2Double(const char* argument);
const char* pan_Double2String(double argument);

/* 20-sim function prototypes */
/* 20-sim stub prototypes */
#endif

